//authentication actions

export const LOGIN = 'LOGIN';

export const REGISTER = 'REGISTER';

export const REGISTER_CONFIRM = 'REGISTER_CONFIRM';

export const RECOVERY_EMAIL = 'RECOVERY_EMAIL';

export const RECOVERY_CONFIRM = 'RECOVERY_CONFIRM';

export const RECOVERY_NEW_PASSWORD = 'RECOVERY_NEW_PASSWORD';

export const RESEND_CODE = 'RESEND_CODE';

export const LOGIN_TWITCH = 'LOGIN_TWITCH';

export const LOGIN_FACEBOOK = 'LOGIN_FACEBOOK';

export const FACEBOOK_EMAIL = 'FACEBOOK_EMAIL';

export const FACEBOOK_EMAIL_CONFIRM = 'FACEBOOK_EMAIL_CONFIRM';

//profile actions

export const PROFILE = 'PROFILE';
export const PROFILE_SUCCESS = 'PROFILE_SUCCESS';
export const PROFILE_FAIL = 'PROFILE_FAIL';

export const PROFILE_PLATFORM = 'PROFILE_PLATFORM';

export const UPDATE_PROFILE = 'UPDATE_PROFILE';

//user actions

export const MY_PROFILE = 'MY_PROFILE';
export const MY_PROFILE_SUCCESS = 'MY_PROFILE_SUCCESS';
export const MY_PROFILE_FAIL = 'MY_PROFILE_FAIL';

export const EDIT_MY_PROFILE = 'EDIT_MY_PROFILE';
export const EDIT_MY_PROFILE_SUCCESS = 'EDIT_MY_PROFILE_SUCCESS';
export const EDIT_MY_PROFILE_FAIL = 'EDIT_MY_PROFILE_FAIL';

export const CHANGE_PASSWORD = 'CHANGE_PASSWORD';

export const PREFERENCES = 'PREFERENCES';
export const PREFERENCES_SUCCESS = 'PREFERENCES_SUCCESS';
export const PREFERENCES_FAIL = 'PREFERENCES_FAIL';

export const SET_PREFERENCES = 'SET_PREFERENCES';
export const SET_PREFERENCES_SUCCESS = 'SET_PREFERENCES_SUCCESS';
export const SET_PREFERENCES_FAIL = 'SET_PREFERENCES_FAIL';

export const USER_PROFILE = 'USER_PROFILE';
export const USER_PROFILE_SUCCESS = 'USER_PROFILE_SUCCESS';
export const USER_PROFILE_FAIL = 'USER_PROFILE_FAIL';

export const UPDATE_USER_PROFILE = 'UPDATE_USER_PROFILE';

//leaderboard actions

export const LEADERBOARD = 'LEADERBOARD';
export const LEADERBOARD_SUCCESS = 'LEADERBOARD_SUCCESS';
export const LEADERBOARD_FAIL = 'LEADERBOARD_FAIL';

//friends actions

export const FRIENDS_LIST = 'FRIENDS_LIST';
export const FRIENDS_LIST_SUCCESS = 'FRIENDS_LIST_SUCCESS';
export const FRIENDS_LIST_FAIL = 'FRIENDS_LIST_FAIL';

export const SEARCH_USERS = 'SEARCH_USERS';
export const SEARCH_USERS_SUCCESS = 'SEARCH_USERS_SUCCESS';
export const SEARCH_USERS_FAIL = 'SEARCH_USERS_FAIL';

export const SEARCH_FRIENDS = 'SEARCH_FRIENDS';
export const SEARCH_FRIENDS_SUCCESS = 'SEARCH_FRIENDS_SUCCESS';
export const SEARCH_FRIENDS_FAIL = 'SEARCH_FRIENDS_FAIL';

export const ADD_TO_FRIENDS = 'ADD_TO_FRIENDS';

export const FRIENDS_REQUESTS = 'FRIENDS_REQUESTS';
export const FRIENDS_REQUESTS_SUCCESS = 'FRIENDS_REQUESTS_SUCCESS';
export const FRIENDS_REQUESTS_FAIL = 'FRIENDS_REQUESTS_FAIL';

export const ACCEPT_FRIEND_REQUEST = 'ACCEPT_FRIEND_REQUEST';

export const REMOVE_FRIEND = 'REMOVE_FRIEND';

//intro actions

export const INTRO = 'INTRO';
export const INTRO_SUCCESS = 'INTRO_SUCCESS';
export const INTRO_FAIL = 'INTRO_FAIL';

export const UPDATE_INTRO = 'UPDATE_INTRO';

export const INTRO_PLATFORMS = 'INTRO_PLATFORMS';
export const INTRO_PLATFORMS_SUCCESS = 'INTRO_PLATFORMS_SUCCESS';
export const INTRO_PLATFORMS_FAIL = 'INTRO_PLATFORMS_FAIL';

export const INTRO_PATCH_PLATFORM = 'INTRO_PATCH_PLATFORM';

export const UPDATE_INTRO_PPLATFORM = 'UPDATE_INTRO_PPLATFORM';

export const CREDITS_VIDEO = 'CREDITS_VIDEO';
export const CREDITS_VIDEO_SUCCESS = 'CREDITS_VIDEO_SUCCESS';
export const CREDITS_VIDEO_FAIL = 'CREDITS_VIDEO_FAIL';

export const PATCH_INTRO = 'PATCH_INTRO';
export const PATCH_INTRO_SUCCESS = 'PATCH_INTRO_SUCCESS';

//game center actions

export const USERS_ONLINE = 'USERS_ONLINE';
export const USERS_ONLINE_SUCCESS = 'USERS_ONLINE_SUCCESS';
export const USERS_ONLINE_FAIL = 'USERS_ONLINE_FAIL';

export const CENTER_INFO = 'CENTER_INFO';
export const CENTER_INFO_SUCCESS = 'CENTER_INFO_SUCCESS';
export const CENTER_INFO_FAIL = 'CENTER_INFO_FAIL';

export const START_CREATE_GAME = 'START_CREATE_GAME';
export const START_CREATE_GAME_SUCCESS = 'START_CREATE_GAME_SUCCESS';
export const START_CREATE_GAME_FAIL = 'START_CREATE_GAME_FAIL';

export const SET_GAME_DATA = 'SET_GAME_DATA';

export const UPLOAD_RESULT = 'UPLOAD_RESULT';
export const UPLOAD_RESULT_SUCCESS = 'UPLOAD_RESULT_SUCCESS';
export const UPLOAD_RESULT_FAIL = 'UPLOAD_RESULT_FAIL';

export const DELETE_SELECT_FRIEND = 'DELETE_SELECT_FRIEND';

export const DELETE_INVITE_FRIEND = 'DELETE_INVITE_FRIEND';

export const SELECT_FRIEND_FOR_GAME = 'SELECT_FRIEND_FOR_GAME';

export const INVITE_FRIEND_FOR_GAME = 'INVITE_FRIEND_FOR_GAME';

export const GAME_FRIEND_REQUEST = 'GAME_FRIEND_REQUEST';
export const GAME_FRIEND_REQUEST_SUCCESS = 'GAME_FRIEND_REQUEST_SUCCESS';
export const GAME_FRIEND_REQUEST_FAIL = 'GAME_FRIEND_REQUEST_FAIL';

export const GAME_FRIEND_REQUEST_ACCEPT = 'GAME_FRIEND_REQUEST_ACCEPT';
export const GAME_FRIEND_REQUEST_ACCEPT_SUCCESS = 'GAME_FRIEND_REQUEST_ACCEPT_SUCCESS';
export const GAME_FRIEND_REQUEST_ACCEPT_FAIL = 'GAME_FRIEND_REQUEST_ACCEPT_FAIL';

export const GAME_FRIEND_REQUEST_CANCEL = 'GAME_FRIEND_REQUEST_CANCEL';

export const GAME_REMATCH_REQUEST = 'GAME_REMATCH_REQUEST';
export const GAME_REMATCH_REQUEST_SUCCESS = 'GAME_REMATCH_REQUEST_SUCCESS';
export const GAME_REMATCH_REQUEST_FAIL = 'GAME_REMATCH_REQUEST_FAIL';

export const GAME_REMATCH_REQUEST_ACCEPT = 'GAME_REMATCH_REQUEST_ACCEPT';
export const GAME_REMATCH_REQUEST_ACCEPT_SUCCESS = 'GAME_REMATCH_REQUEST_ACCEPT_SUCCESS';
export const GAME_REMATCH_REQUEST_ACCEPT_FAIL = 'GAME_REMATCH_REQUEST_ACCEPT_FAIL';

export const GAME_REMATCH_REQUEST_CANCEL = 'GAME_REMATCH_REQUEST_CANCEL';

export const START_FRIEND_GAME = 'START_FRIEND_GAME';
export const START_FRIEND_GAME_SUCCESS = 'START_FRIEND_GAME_SUCCESS';
export const START_FRIEND_GAME_FAIL = 'START_FRIEND_GAME_FAIL';

//notifications actions

export const SET_NOTIFICATIONS_SECTIONS = 'SET_NOTIFICATIONS_SECTIONS';

export const GET_NOTIFICATIONS = 'GET_NOTIFICATIONS';
export const GET_NOTIFICATIONS_SUCCESS = 'GET_NOTIFICATIONS_SUCCESS';
export const GET_NOTIFICATIONS_FAIL = 'GET_NOTIFICATIONS_FAIL';

export const CLEAR_NOTIFICATIONS = 'CLEAR_NOTIFICATIONS';

export const DELETE_NOTIFICATION = 'DELETE_NOTIFICATION';

export const UPDATE_NOTIFICATIONS_SECTIONS = 'UPDATE_NOTIFICATIONS_SECTIONS';
export const UPDATE_NOTIFICATIONS_SECTIONS_SUCCESS = 'UPDATE_NOTIFICATIONS_SECTIONS_SUCCESS';
export const UPDATE_NOTIFICATIONS_SECTIONS_FAIL = 'UPDATE_NOTIFICATIONS_SECTIONS_FAIL';

//chat actions

export const GET_CHATS_LIST = 'GET_CHATS_LIST';
export const GET_CHATS_LIST_SUCCESS = 'GET_CHATS_LIST_SUCCESS';
export const GET_CHATS_LIST_FAIL = 'GET_CHATS_LIST_FAIL';

export const SELECT_CHAT = 'SELECT_CHAT';

export const GET_CHAT_MESSAGES = 'GET_CHAT_MESSAGES';
export const GET_CHAT_MESSAGES_SUCCESS = 'GET_CHAT_MESSAGES_SUCCESS';
export const GET_CHAT_MESSAGES_FAIL = 'GET_CHAT_MESSAGES_FAIL';

export const UPDATE_MESSAGE_LIST = 'UPDATE_MESSAGE_LIST';

export const POST_CHAT_IMAGE = 'POST_CHAT_IMAGE';
export const POST_CHAT_IMAGE_SUCCESS = 'POST_CHAT_IMAGE_SUCCESS';
export const POST_CHAT_IMAGE_FAIL = 'POST_CHAT_IMAGE_FAIL';

export const UPDATE_CHATS_READ = 'UPDATE_CHATS_READ';

export const GET_CHAT_USERS_STATUS = 'GET_CHAT_USERS_STATUS';
export const GET_CHAT_USERS_STATUS_SUCCESS = 'GET_CHAT_USERS_STATUS_SUCCESS';
export const GET_CHAT_USERS_STATUS_FAIL = 'GET_CHAT_USERS_STATUS_FAIL';

//dispute action

export const DISPUTES_LIST = 'DISPUTES_LIST';
export const DISPUTES_LIST_SUCCESS = 'DISPUTES_LIST_SUCCESS';
export const DISPUTES_LIST_FAIL = 'DISPUTES_LIST_FAIL';

export const DISPUTE_DETAIL = 'DISPUTE_DETAIL';
export const DISPUTE_DETAIL_SUCCESS = 'DISPUTE_DETAIL_SUCCESS';
export const DISPUTE_DETAIL_FAIL = 'DISPUTE_DETAIL_FAIL';

export const DISPUTE_MESSAGES = 'DISPUTE_MESSAGES';
export const DISPUTE_MESSAGES_SUCCESS = 'DISPUTE_MESSAGES_SUCCESS';
export const DISPUTE_MESSAGES_FAIL = 'DISPUTE_MESSAGES_FAIL';

export const UPDATE_DISPUTE_MESSAGE_LIST = 'UPDATE_DISPUTE_MESSAGE_LIST';

export const UPDATE_DISPUTE_RESULT = 'UPDATE_DISPUTE_RESULT';

//challenges actions

export const CHALLENGES_LIST = 'CHALLENGES_LIST';
export const CHALLENGES_LIST_SUCCESS = 'CHALLENGES_LIST_SUCCESS';
export const CHALLENGES_LIST_FAIL = 'CHALLENGES_LIST_FAIL';

export const CHALLENGE_REWARD = 'CHALLENGE_REWARD';
export const CHALLENGE_REWARD_SUCCESS = 'CHALLENGE_REWARD_SUCCESS';
export const CHALLENGE_REWARD_FAIL = 'CHALLENGE_REWARD_FAIL';

//info actions

export const GET_FAQ = 'GET_FAQ';
export const GET_FAQ_SUCCESS = 'GET_FAQ_SUCCESS';
export const GET_FAQ_FAIL = 'GET_FAQ_FAIL';

export const GET_INFO = 'GET_INFO';
export const GET_INFO_SUCCESS = 'GET_INFO_SUCCESS';
export const GET_INFO_FAIL = 'GET_INFO_FAIL';

export const SUPPORT = 'SUPPORT';
export const SUPPORT_SUCCESS = 'SUPPORT_SUCCESS';
export const SUPPORT_FAIL = 'SUPPORT_FAIL';

export const GAMES_LIST = 'GAMES_LIST';
export const GAMES_LIST_SUCCESS = 'GAMES_LIST_SUCCESS';
export const GAMES_LIST_FAIL = 'GAMES_LIST_FAIL';

export const GAME_RULES = 'GAME_RULES';
export const GAME_RULES_SUCCESS = 'GAME_RULES_SUCCESS';
export const GAME_RULES_FAIL = 'GAME_RULES_FAIL';

//wallet actions

export const USE_PROMOCODE = 'USE_PROMOCODE';
export const USE_PROMOCODE_SUCCESS = 'USE_PROMOCODE_SUCCESS';
export const USE_PROMOCODE_FAIL = 'USE_PROMOCODE_FAIL';

export const TRANSACTIONS = 'TRANSACTIONS';
export const TRANSACTIONS_SUCCESS = 'TRANSACTIONS_SUCCESS';
export const TRANSACTIONS_FAIL = 'TRANSACTIONS_FAIL';

export const WALLET_GAMES = 'WALLET_GAMES';
export const WALLET_GAMES_SUCCESS = 'WALLET_GAMES_SUCCESS';
export const WALLET_GAMES_FAIL = 'WALLET_GAMES_FAIL';

export const SET_WALLET_DATA = 'CLEAR_WALLET_DATA';

export const CREATE_DEPOSIT = 'CREATE_DEPOSIT';
export const CREATE_DEPOSIT_SUCCESS = 'CREATE_DEPOSIT_SUCCESS';
export const CREATE_DEPOSIT_FAIL = 'CREATE_DEPOSIT_FAIL';

export const EXECUTE_DEPOSIT = 'EXECUTE_DEPOSIT';
export const EXECUTE_DEPOSIT_SUCCESS = 'EXECUTE_DEPOSIT_SUCCESS';
export const EXECUTE_DEPOSIT_FAIL = 'EXECUTE_DEPOSIT_FAIL';

export const CREATE_WITHDRAW = 'CREATE_WITHDRAW';
export const CREATE_WITHDRAW_SUCCESS = 'CREATE_WITHDRAW_SUCCESS';
export const CREATE_WITHDRAW_FAIL = 'CREATE_WITHDRAW_FAIL';